'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { slugify } from '@/lib/utils';
import { BlogPost } from '@prisma/client';
import { useAdminLocale } from '@/contexts/AdminLocaleContext';

interface BlogFormProps {
  post?: BlogPost;
}

export default function BlogForm({ post }: BlogFormProps) {
  const router = useRouter();
  const { toast } = useToast();
  const { t } = useAdminLocale();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    slug: post?.slug || '',
    titleTr: post?.titleTr || '',
    titleEn: post?.titleEn || '',
    excerptTr: post?.excerptTr || '',
    excerptEn: post?.excerptEn || '',
    contentTr: post?.contentTr || '',
    contentEn: post?.contentEn || '',
    author: post?.author || 'Elma Vize',
    category: post?.category || 'Genel',
    published: post?.published || false,
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value, type } = e.target;
    
    setFormData((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? (e.target as HTMLInputElement).checked : value,
    }));

    if (name === 'titleEn' && !post) {
      setFormData((prev) => ({
        ...prev,
        slug: slugify(value),
      }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const url = post
        ? `/api/admin/blog/${post.id}`
        : '/api/admin/blog';
      
      const method = post ? 'PUT' : 'POST';

      const response = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        throw new Error('Failed to save blog post');
      }

      toast({
        title: 'Success',
        description: `Blog post ${post ? 'updated' : 'created'} successfully`,
      });

      router.push('/admin/blog');
      router.refresh();
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to save blog post',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>{t.forms.basicInfo}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="titleEn">{t.forms.titleEn} *</Label>
              <Input
                id="titleEn"
                name="titleEn"
                value={formData.titleEn}
                onChange={handleChange}
                required
                placeholder="Guide to Studying Abroad"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="titleTr">{t.forms.titleTr} *</Label>
              <Input
                id="titleTr"
                name="titleTr"
                value={formData.titleTr}
                onChange={handleChange}
                required
                placeholder="Yurtdışında Eğitim Rehberi"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug">{t.forms.slug} *</Label>
            <Input
              id="slug"
              name="slug"
              value={formData.slug}
              onChange={handleChange}
              required
              placeholder="guide-to-studying-abroad"
            />
            <p className="text-sm text-gray-500">
              {t.forms.autoGenerated}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="author">{t.blog.author}</Label>
              <Input
                id="author"
                name="author"
                value={formData.author}
                onChange={handleChange}
                placeholder="Elma Vize"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="category">Category</Label>
              <Input
                id="category"
                name="category"
                value={formData.category}
                onChange={handleChange}
                placeholder="Genel, Eğitim, Vize, etc."
              />
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <input
              type="checkbox"
              id="published"
              name="published"
              checked={formData.published}
              onChange={handleChange}
              className="w-4 h-4 rounded border-gray-300"
            />
            <Label htmlFor="published" className="cursor-pointer">
              {t.forms.publishedVisible}
            </Label>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>{t.forms.shortExcerpt}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="excerptEn">{t.forms.excerptEn}</Label>
            <Textarea
              id="excerptEn"
              name="excerptEn"
              value={formData.excerptEn}
              onChange={handleChange}
              rows={3}
              placeholder="Brief summary for blog listing page..."
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="excerptTr">Excerpt (Turkish)</Label>
            <Textarea
              id="excerptTr"
              name="excerptTr"
              value={formData.excerptTr}
              onChange={handleChange}
              rows={3}
              placeholder="Blog listesi için kısa özet..."
            />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>{t.forms.fullContent}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="contentEn">Content (English) *</Label>
            <Textarea
              id="contentEn"
              name="contentEn"
              value={formData.contentEn}
              onChange={handleChange}
              rows={15}
              required
              placeholder="Enter full blog post content in English..."
            />
            <p className="text-sm text-gray-500">
              {t.forms.htmlTags}
            </p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="contentTr">{t.forms.contentTr} *</Label>
            <Textarea
              id="contentTr"
              name="contentTr"
              value={formData.contentTr}
              onChange={handleChange}
              rows={15}
              required
              placeholder="Türkçe blog yazısı içeriğini girin..."
            />
            <p className="text-sm text-gray-500">
              {t.forms.htmlTags}
            </p>
          </div>
        </CardContent>
      </Card>

      <div className="flex items-center justify-end space-x-4">
        <Button
          type="button"
          variant="outline"
          onClick={() => router.push('/admin/blog')}
          disabled={isSubmitting}
        >
          {t.common.cancel}
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? t.common.saving : post ? t.common.update : t.common.create}
        </Button>
      </div>
    </form>
  );
}
