'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { slugify } from '@/lib/utils';
import { Country } from '@prisma/client';
import { useAdminLocale } from '@/contexts/AdminLocaleContext';

interface CountryFormProps {
  country?: Country;
}

export default function CountryForm({ country }: CountryFormProps) {
  const router = useRouter();
  const { toast } = useToast();
  const { t } = useAdminLocale();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    slug: country?.slug || '',
    nameTr: country?.nameTr || '',
    nameEn: country?.nameEn || '',
    descriptionTr: country?.descriptionTr || '',
    descriptionEn: country?.descriptionEn || '',
    contentTr: country?.contentTr || '',
    contentEn: country?.contentEn || '',
    flagImage: country?.flagImage || '',
    featured: country?.featured || false,
    order: country?.order || 0,
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value, type } = e.target;
    
    setFormData((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? (e.target as HTMLInputElement).checked : value,
    }));

    // Auto-generate slug from English name
    if (name === 'nameEn' && !country) {
      setFormData((prev) => ({
        ...prev,
        slug: slugify(value),
      }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const url = country
        ? `/api/admin/countries/${country.id}`
        : '/api/admin/countries';
      
      const method = country ? 'PUT' : 'POST';

      const response = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        throw new Error('Failed to save country');
      }

      toast({
        title: 'Success',
        description: `Country ${country ? 'updated' : 'created'} successfully`,
      });

      router.push('/admin/countries');
      router.refresh();
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to save country',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Basic Information */}
      <Card>
        <CardHeader>
          <CardTitle>{t.forms.basicInfo}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="nameEn">{t.forms.nameEn} *</Label>
              <Input
                id="nameEn"
                name="nameEn"
                value={formData.nameEn}
                onChange={handleChange}
                required
                placeholder="Germany"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="nameTr">{t.forms.nameTr} *</Label>
              <Input
                id="nameTr"
                name="nameTr"
                value={formData.nameTr}
                onChange={handleChange}
                required
                placeholder="Almanya"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug">{t.forms.slug} *</Label>
            <Input
              id="slug"
              name="slug"
              value={formData.slug}
              onChange={handleChange}
              required
              placeholder="germany"
            />
            <p className="text-sm text-gray-500">
              {t.forms.autoGenerated}
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="flagImage">Flag Image URL (optional)</Label>
            <Input
              id="flagImage"
              name="flagImage"
              value={formData.flagImage}
              onChange={handleChange}
              placeholder="https://example.com/flag.png"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="featured"
                name="featured"
                checked={formData.featured}
                onChange={handleChange}
                className="w-4 h-4 rounded border-gray-300"
              />
              <Label htmlFor="featured" className="cursor-pointer">
                {t.forms.featuredHomepage}
              </Label>
            </div>
            <div className="space-y-2">
              <Label htmlFor="order">{t.forms.displayOrder}</Label>
              <Input
                type="number"
                id="order"
                name="order"
                value={formData.order}
                onChange={handleChange}
                placeholder="0"
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Descriptions */}
      <Card>
        <CardHeader>
          <CardTitle>Short Description</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="descriptionEn">{t.forms.descriptionEn}</Label>
            <Textarea
              id="descriptionEn"
              name="descriptionEn"
              value={formData.descriptionEn}
              onChange={handleChange}
              rows={2}
              placeholder="Work and living opportunities in the heart of Europe"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="descriptionTr">Description (Turkish)</Label>
            <Textarea
              id="descriptionTr"
              name="descriptionTr"
              value={formData.descriptionTr}
              onChange={handleChange}
              rows={2}
              placeholder="Avrupa'nın kalbinde çalışma ve yaşam fırsatları"
            />
          </div>
        </CardContent>
      </Card>

      {/* Full Content */}
      <Card>
        <CardHeader>
          <CardTitle>{t.forms.fullContent}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="contentEn">Content (English)</Label>
            <Textarea
              id="contentEn"
              name="contentEn"
              value={formData.contentEn}
              onChange={handleChange}
              rows={8}
              placeholder="Enter full content in English..."
            />
            <p className="text-sm text-gray-500">
              {t.forms.htmlTags}
            </p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="contentTr">{t.forms.contentTr}</Label>
            <Textarea
              id="contentTr"
              name="contentTr"
              value={formData.contentTr}
              onChange={handleChange}
              rows={8}
              placeholder="Türkçe tam içeriği girin..."
            />
            <p className="text-sm text-gray-500">
              HTML etiketlerini kullanabilirsiniz
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Actions */}
      <div className="flex items-center justify-end space-x-4">
        <Button
          type="button"
          variant="outline"
          onClick={() => router.push('/admin/countries')}
          disabled={isSubmitting}
        >
          {t.common.cancel}
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? t.common.saving : country ? t.common.update : t.common.create}
        </Button>
      </div>
    </form>
  );
}
