'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useToast } from '@/hooks/use-toast';
import { slugify } from '@/lib/utils';
import { Country } from '@prisma/client';
import { useAdminLocale } from '@/contexts/AdminLocaleContext';
import * as Flags from 'country-flag-icons/react/3x2';
import { Upload, Link as LinkIcon } from 'lucide-react';
import ImageUpload from './ImageUpload';

interface CountryFormProps {
  country?: Country;
}

export default function CountryForm({ country }: CountryFormProps) {
  const router = useRouter();
  const { toast } = useToast();
  const { t } = useAdminLocale();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    slug: country?.slug || '',
    nameTr: country?.nameTr || '',
    nameEn: country?.nameEn || '',
    descriptionTr: country?.descriptionTr || '',
    descriptionEn: country?.descriptionEn || '',
    contentTr: country?.contentTr || '',
    contentEn: country?.contentEn || '',
    flagImage: country?.flagImage || '',
    iso2Code: country?.iso2Code || '',
    featuredImage: country?.featuredImage || '',
    featured: country?.featured || false,
    order: country?.order || 0,
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value, type } = e.target;
    
    setFormData((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? (e.target as HTMLInputElement).checked : value,
    }));

    // Auto-generate slug from English name
    if (name === 'nameEn' && !country) {
      setFormData((prev) => ({
        ...prev,
        slug: slugify(value),
      }));
    }
  };

  const handleSelectChange = (name: string, value: string) => {
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const url = country
        ? `/api/admin/countries/${country.id}`
        : '/api/admin/countries';
      
      const method = country ? 'PUT' : 'POST';

      const response = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        throw new Error('Failed to save country');
      }

      toast({
        title: 'Success',
        description: `Country ${country ? 'updated' : 'created'} successfully`,
      });

      router.push('/admin/countries');
      router.refresh();
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to save country',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Basic Information */}
      <Card>
        <CardHeader>
          <CardTitle>{t.forms.basicInfo}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="nameEn">{t.forms.nameEn} *</Label>
              <Input
                id="nameEn"
                name="nameEn"
                value={formData.nameEn}
                onChange={handleChange}
                required
                placeholder="Germany"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="nameTr">{t.forms.nameTr} *</Label>
              <Input
                id="nameTr"
                name="nameTr"
                value={formData.nameTr}
                onChange={handleChange}
                required
                placeholder="Almanya"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug">{t.forms.slug} *</Label>
            <Input
              id="slug"
              name="slug"
              value={formData.slug}
              onChange={handleChange}
              required
              placeholder="germany"
            />
            <p className="text-sm text-gray-500">
              {t.forms.autoGenerated}
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="iso2Code">{t.forms.isoCode || 'ISO Country Code'}</Label>
            <div className="flex items-center gap-4">
              {formData.iso2Code && (
                <div className="w-20 h-15 border rounded flex items-center justify-center bg-gray-50">
                  {React.createElement((Flags as any)[formData.iso2Code], { 
                    className: "w-full h-full object-contain" 
                  })}
                </div>
              )}
              <Select 
                value={formData.iso2Code} 
                onValueChange={(value) => handleSelectChange('iso2Code', value)}
              >
                <SelectTrigger className="flex-1">
                  <SelectValue placeholder={t.forms.selectIsoCode || 'Select ISO code'} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="US">🇺🇸 United States (US)</SelectItem>
                  <SelectItem value="DE">🇩🇪 Germany (DE)</SelectItem>
                  <SelectItem value="CA">🇨🇦 Canada (CA)</SelectItem>
                  <SelectItem value="GB">🇬🇧 United Kingdom (GB)</SelectItem>
                  <SelectItem value="TR">🇹🇷 Turkey (TR)</SelectItem>
                  <SelectItem value="FR">🇫🇷 France (FR)</SelectItem>
                  <SelectItem value="ES">🇪🇸 Spain (ES)</SelectItem>
                  <SelectItem value="IT">🇮🇹 Italy (IT)</SelectItem>
                  <SelectItem value="NL">🇳🇱 Netherlands (NL)</SelectItem>
                  <SelectItem value="AU">🇦🇺 Australia (AU)</SelectItem>
                  <SelectItem value="NZ">🇳🇿 New Zealand (NZ)</SelectItem>
                  <SelectItem value="JP">🇯🇵 Japan (JP)</SelectItem>
                  <SelectItem value="KR">🇰🇷 South Korea (KR)</SelectItem>
                  <SelectItem value="CN">🇨🇳 China (CN)</SelectItem>
                  <SelectItem value="IE">🇮🇪 Ireland (IE)</SelectItem>
                  <SelectItem value="AT">🇦🇹 Austria (AT)</SelectItem>
                  <SelectItem value="CH">🇨🇭 Switzerland (CH)</SelectItem>
                  <SelectItem value="BE">🇧🇪 Belgium (BE)</SelectItem>
                  <SelectItem value="SE">🇸🇪 Sweden (SE)</SelectItem>
                  <SelectItem value="NO">🇳🇴 Norway (NO)</SelectItem>
                  <SelectItem value="DK">🇩🇰 Denmark (DK)</SelectItem>
                  <SelectItem value="FI">🇫🇮 Finland (FI)</SelectItem>
                  <SelectItem value="PL">🇵🇱 Poland (PL)</SelectItem>
                  <SelectItem value="PT">🇵🇹 Portugal (PT)</SelectItem>
                  <SelectItem value="GR">🇬🇷 Greece (GR)</SelectItem>
                  <SelectItem value="CZ">🇨🇿 Czech Republic (CZ)</SelectItem>
                  <SelectItem value="HU">🇭🇺 Hungary (HU)</SelectItem>
                  <SelectItem value="RO">🇷🇴 Romania (RO)</SelectItem>
                  <SelectItem value="BG">🇧🇬 Bulgaria (BG)</SelectItem>
                  <SelectItem value="HR">🇭🇷 Croatia (HR)</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <p className="text-sm text-gray-500">
              {t.forms.isoCodeHelp || 'Select the 2-letter ISO country code for automatic flag display'}
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="flagImage">Flag Image URL (optional)</Label>
            <Input
              id="flagImage"
              name="flagImage"
              value={formData.flagImage}
              onChange={handleChange}
              placeholder="https://example.com/flag.png"
            />
            <p className="text-sm text-gray-500">
              Not needed if ISO code is selected above
            </p>
          </div>

          <div className="space-y-2">
            <Label>{t.forms.featuredImage || 'Featured Image'} (optional)</Label>
            <Tabs defaultValue="url" className="w-full">
              <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="url">
                  <LinkIcon className="h-4 w-4 mr-2" />
                  URL
                </TabsTrigger>
                <TabsTrigger value="upload">
                  <Upload className="h-4 w-4 mr-2" />
                  Upload
                </TabsTrigger>
              </TabsList>

              <TabsContent value="url" className="space-y-2">
                <Input
                  id="featuredImage"
                  name="featuredImage"
                  value={formData.featuredImage}
                  onChange={handleChange}
                  placeholder="https://images.unsplash.com/photo-..."
                />
                <p className="text-sm text-gray-500">
                  Landmark or landscape photo of the country (1200x800px recommended)
                </p>
              </TabsContent>

              <TabsContent value="upload">
                <ImageUpload
                  value={formData.featuredImage}
                  onChange={(url) => setFormData({ ...formData, featuredImage: url })}
                  onRemove={() => setFormData({ ...formData, featuredImage: '' })}
                  folder="elma-vize/countries"
                  label=""
                  helpText="Landmark or landscape photo of the country (1200x800px recommended)"
                />
              </TabsContent>
            </Tabs>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="featured"
                name="featured"
                checked={formData.featured}
                onChange={handleChange}
                className="w-4 h-4 rounded border-gray-300"
              />
              <Label htmlFor="featured" className="cursor-pointer">
                {t.forms.featuredHomepage}
              </Label>
            </div>
            <div className="space-y-2">
              <Label htmlFor="order">{t.forms.displayOrder}</Label>
              <Input
                type="number"
                id="order"
                name="order"
                value={formData.order}
                onChange={handleChange}
                placeholder="0"
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Descriptions */}
      <Card>
        <CardHeader>
          <CardTitle>Short Description</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="descriptionEn">{t.forms.descriptionEn}</Label>
            <Textarea
              id="descriptionEn"
              name="descriptionEn"
              value={formData.descriptionEn}
              onChange={handleChange}
              rows={2}
              placeholder="Work and living opportunities in the heart of Europe"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="descriptionTr">Description (Turkish)</Label>
            <Textarea
              id="descriptionTr"
              name="descriptionTr"
              value={formData.descriptionTr}
              onChange={handleChange}
              rows={2}
              placeholder="Avrupa'nın kalbinde çalışma ve yaşam fırsatları"
            />
          </div>
        </CardContent>
      </Card>

      {/* Full Content */}
      <Card>
        <CardHeader>
          <CardTitle>{t.forms.fullContent}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="contentEn">Content (English)</Label>
            <Textarea
              id="contentEn"
              name="contentEn"
              value={formData.contentEn}
              onChange={handleChange}
              rows={8}
              placeholder="Enter full content in English..."
            />
            <p className="text-sm text-gray-500">
              {t.forms.htmlTags}
            </p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="contentTr">{t.forms.contentTr}</Label>
            <Textarea
              id="contentTr"
              name="contentTr"
              value={formData.contentTr}
              onChange={handleChange}
              rows={8}
              placeholder="Türkçe tam içeriği girin..."
            />
            <p className="text-sm text-gray-500">
              HTML etiketlerini kullanabilirsiniz
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Actions */}
      <div className="flex items-center justify-end space-x-4">
        <Button
          type="button"
          variant="outline"
          onClick={() => router.push('/admin/countries')}
          disabled={isSubmitting}
        >
          {t.common.cancel}
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? t.common.saving : country ? t.common.update : t.common.create}
        </Button>
      </div>
    </form>
  );
}
