'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';
import { slugify } from '@/lib/utils';
import { Page } from '@prisma/client';
import { useAdminLocale } from '@/contexts/AdminLocaleContext';
import { Upload, Link as LinkIcon } from 'lucide-react';
import ImageUpload from './ImageUpload';
import RichTextEditor from './RichTextEditor';

interface PageFormProps {
  page?: Page;
}

export default function PageForm({ page }: PageFormProps) {
  const router = useRouter();
  const { toast } = useToast();
  const { t } = useAdminLocale();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    slug: page?.slug || '',
    titleTr: page?.titleTr || '',
    titleEn: page?.titleEn || '',
    contentTr: page?.contentTr || '',
    contentEn: page?.contentEn || '',
    featuredImage: page?.featuredImage || '',
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));

    if (name === 'titleEn' && !page) {
      setFormData((prev) => ({
        ...prev,
        slug: slugify(value),
      }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const url = page
        ? `/api/admin/pages/${page.id}`
        : '/api/admin/pages';
      
      const method = page ? 'PUT' : 'POST';

      const response = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        throw new Error('Failed to save page');
      }

      toast({
        title: 'Success',
        description: `Page ${page ? 'updated' : 'created'} successfully`,
      });

      router.push('/admin/pages');
      router.refresh();
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to save page',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>{t.forms.basicInfo}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="titleEn">{t.forms.titleEn} *</Label>
              <Input
                id="titleEn"
                name="titleEn"
                value={formData.titleEn}
                onChange={handleChange}
                required
                placeholder="About Us"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="titleTr">{t.forms.titleTr} *</Label>
              <Input
                id="titleTr"
                name="titleTr"
                value={formData.titleTr}
                onChange={handleChange}
                required
                placeholder="Hakkımızda"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug">Slug (URL) *</Label>
            <Input
              id="slug"
              name="slug"
              value={formData.slug}
              onChange={handleChange}
              required
              placeholder="about-us"
            />
            <p className="text-sm text-gray-500">
              {t.forms.urlWillBe} ({t.forms.autoGenerated})
            </p>
          </div>

          <div className="space-y-2">
            <Label>{t.forms.featuredImage || 'Featured Image'} (optional)</Label>
            <Tabs defaultValue="url" className="w-full">
              <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="url">
                  <LinkIcon className="h-4 w-4 mr-2" />
                  URL
                </TabsTrigger>
                <TabsTrigger value="upload">
                  <Upload className="h-4 w-4 mr-2" />
                  Upload
                </TabsTrigger>
              </TabsList>

              <TabsContent value="url" className="space-y-2">
                <Input
                  id="featuredImage"
                  name="featuredImage"
                  value={formData.featuredImage}
                  onChange={handleChange}
                  placeholder="https://images.unsplash.com/photo-..."
                />
                <p className="text-sm text-gray-500">
                  Page header image (1200x400px recommended)
                </p>
              </TabsContent>

              <TabsContent value="upload">
                <ImageUpload
                  value={formData.featuredImage}
                  onChange={(url) => setFormData({ ...formData, featuredImage: url })}
                  onRemove={() => setFormData({ ...formData, featuredImage: '' })}
                  folder="elma-vize/pages"
                  label=""
                  helpText="Page header image (1200x400px recommended)"
                />
              </TabsContent>
            </Tabs>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>{t.forms.pageContent}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <RichTextEditor
            content={formData.contentEn}
            onChange={(html) => setFormData({ ...formData, contentEn: html })}
            placeholder="Enter full page content in English..."
            label={`${t.forms.contentEn} *`}
          />

          <RichTextEditor
            content={formData.contentTr}
            onChange={(html) => setFormData({ ...formData, contentTr: html })}
            placeholder="Türkçe sayfa içeriğini girin..."
            label="Content (Turkish) *"
          />
        </CardContent>
      </Card>

      <div className="flex items-center justify-end space-x-4">
        <Button
          type="button"
          variant="outline"
          onClick={() => router.push('/admin/pages')}
          disabled={isSubmitting}
        >
          {t.common.cancel}
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? t.common.saving : page ? t.common.update : t.common.create}
        </Button>
      </div>
    </form>
  );
}
